CREATE TABLE IF NOT EXISTS support_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    last_message_at TIMESTAMP WITH TIME ZONE,
    author_id BIGINT NOT NULL,
    chat_id BIGINT NOT NULL,
    status VARCHAR(50) NOT NULL,
    FOREIGN KEY (author_id) REFERENCES telegram_users(id)
);