# src/main/resources/application-prod.yml
spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_DOCKER_CONTAINER_NAME}:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}


crm:
  telegram:
    # ID пользователя CRM, который представляет нашего Telegram-бота в чате
    answer-from-bot-id: 8234682964 #amveraCRMBot