# src/main/resources/application.yml
spring:
  application.name: WordsGameSpring

  jpa:
    defer-datasource-initialization: true
    show_sql: false
    properties:
      hibernate:
        format_sql: true
  #      ddl-auto: validate
        ddl-auto: none

  datasource:
    driver-class-name: org.postgresql.Driver


  liquibase:
    enabled: false
    change-log: classpath:/db/changelog/db.changelog-master.yaml


logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
    org.mapstruct: DEBUG
  pattern:
    console: "%d{HH:mm:ss} %highlight(%-5level) | %-50msg - %-15logger{15}%n"

application:
  passwords:
    users:
      ivan: ${IVAN_CRM_PASSWORD}
      kirill: ${KIRILL_CRM_PASSWORD}
      latuk: ${LATUK_CRM_PASSWORD}
    update-passwords: ${UPDATE_PASSWORDS:false}

  antispam:
    url: "https://spam-protect-testamvera.amvera.io/api/check"
    bearer-token: ${ANTISPAM_API_TOKEN}

  telegram:
    username: ${TELEGRAM_USERNAME}
    token: ${TELEGRAM_TOKEN}


